import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import Footer from "@/components/Footer";
import { itcAvanteGarde } from "@/fonts/ItcAvantGarde";
import { bigNoodleTitling } from "@/fonts/BigNoodleTitling";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-foreground ${itcAvanteGarde.className} ${bigNoodleTitling.variable} antialiased`}
      >
        {/* <Theme> */}
        <Navbar />
        {children}
        <Footer />
        {/* </Theme> */}
      </body>
    </html>
  );
}
